services:

  frontend:
    build:
      context: ./frontend

    ports:
      - 3000:80

    networks:
      - backend

    depends_on:
      server-service:
        condition: service_started
    
    profiles:
      - production

  server-service:
    build:
      context: .
      dockerfile: ./Services/Server/Dockerfile
    
    hostname: server-host
    env_file:
      - ./Services/Server/server_secrets.env

    container_name: server

    ports:
      - 5000:8080

    networks:
      - backend

  postgres:
    image: postgres:16
    container_name: postgres

    env_file:
      - ./infrastructure/postgres/postgres.env
    
    ports:
      - 5432:5432

    networks:
      - backend

    volumes:
      - postgres_data:/var/lib/postgresql/data


networks:
  backend:
    driver: bridge

volumes:
  postgres_data: